---
#yml file from Samodelkin
#two2 services
version: '2'
services:
  maven:
#    image: library/maven:3.6.3-openjdk-11
    build:
      context: .
      dockerfile: Dockerfile-mav
    volumes:
      - war:/home/user/box/target/
  tomcat8:
    volumes:
      - war:/usr/local/tomcat/apache-tomcat-7.0.104/webapps
#    image: tomcat:7-jdk8-openjdk-slim
    build:
      context: .
      dockerfile: Dockerfile-tom1
    links:
      - maven
    ports:
      - "8080:8080"
volumes:
 war:






